DROP DATABASE IF EXISTS swiss_post;
CREATE DATABASE swiss_post;
USE swiss_post;

CREATE TABLE data (
 data1 SMALLINT UNSIGNED NOT NULL,
 data2 TINYINT UNSIGNED NOT NULL,
 data3 SMALLINT UNSIGNED NOT NULL,
 data4 TINYINT UNSIGNED NOT NULL,
 data5 VARCHAR(18) NOT NULL,
 data6 VARCHAR(27) NOT NULL,
 data7 CHAR(2) NOT NULL,

 PRIMARY KEY(data1)
);

LOAD DATA INFILE 'C:/Program Files/MariaDB 10.6/Aufgabe6.3/plz_l_20130901/plz_richtig.txt' INTO TABLE data FIELDS TERMINATED BY ','; 